- hosts: all
  name: "Docker Playbook"
  gather_facts: no
  become: true

  vars_files:
    - ./molecule_vars.default.yml
    - ./molecule_vars.config.yml

  roles:
    # System Config
    - { role: classyllama.boilerplate }
    - { role: classyllama.python, tags: python}

  tasks:
    - name: Docker Installation | Install yum utils
      ansible.builtin.yum:
        name: yum-utils
        state: latest

    - name: Docker Installation | Add Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Docker Installation | Enable Docker Edge repo
      ansible.builtin.ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Docker Installation | Enable Docker Test repo
      ansible.builtin.ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Docker Installation | Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: latest
      become: yes

    - name: Docker Installation | Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Docker Installation | Add user molecule to docker group
      ansible.builtin.user:
        name: molecule
        groups: docker
        append: yes
      become: yes
